version: "3"

services:
  app:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/home/my-user/app
    extra_hosts:
      - host.docker.internal:host-gateway

  db:
    image: postgres:15.8-alpine
    container_name: codetube-studio-db
    restart: always
    tty: true
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=codetube_studio
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  pgadmin:
    image: dpage/pgadmin4:8.12.0
    container_name: codetube-studio-pgadmin
    restart: always
    tty: true
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@user.com
      - PGADMIN_DEFAULT_PASSWORD=secret
    ports:
      - "5050:80"
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  db_data: {}
  pgadmin_data: {}
