version: '3'

services:
  app:
    build: .
    container_name: codetube-transcoder-app
    volumes:
      - .:/app
      - external-storage:/media/uploads
    environment:
      - POSTGRES_HOST=host.docker.internal
      - POSTGRES_PORT=5431
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DBNAME=codetube_transcoder
      - POSTGRES_SSLMODE=disable
      - RABBITMQ_URL=amqp://guest:guest@host.docker.internal:5672
      - CONVERSION_EXCHANGE=conversion_exchange
      - CONVERSION_QUEUE=conversion_queue
      - CONVERSION_KEY=conversion_key
      - CONFIRMATION_KEY=confirmation_key
      - CONFIRMATION_QUEUE=confirmation_queue
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    image: postgres:15.8-alpine
    container_name: codetube-transcoder-db
    restart: always
    tty: true
    volumes:
      - .docker/postgres/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=codetube_transcoder
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - "5431:5432"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  pgadmin:
    image: dpage/pgadmin4:8.12.0
    container_name: codetube-transcoder-pgadmin
    restart: always
    tty: true
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@user.com
      - PGADMIN_DEFAULT_PASSWORD=secret
    ports:
      - "5151:80"
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: codetube-transcoder-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  db_data: {}
  pgadmin_data: {}
  external-storage:
    external: true
